name: flutter_doc_scanner
description: "A Flutter plugin for document scanning on Android, iOS, and other platforms using ML Kit Document Scanner API, VisionKit, and platform-specific implementations."
version: 0.0.15
homepage: https://github.com/shirsh94/flutter_doc_scanner/

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shirsh.flutter_doc_scanner
        pluginClass: FlutterDocScannerPlugin
      ios:
        pluginClass: SwiftFlutterDocScannerPlugin
      linux:
        pluginClass: FlutterDocScannerPlugin
      macos:
        pluginClass: FlutterDocScannerPlugin
      windows:
        pluginClass: FlutterDocScannerPlugin
        fileName: flutter_doc_scanner_plugin.cpp
      web:
        pluginClass: FlutterDocScannerWeb
        fileName: flutter_doc_scanner_web.dart

  # Uncomment and configure assets if your plugin requires specific resources.
  # assets:
  #   - images/example_image.png

  # Uncomment and configure fonts if needed for your plugin.
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
